spring:
  application:
    name: hello-client

server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

hello-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8091,localhost:8092
    ServerListRefreshInterval: 15000
